# Form implementation generated from reading ui file 'interface_breaker.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setMaximumSize(QtCore.QSize(600, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget.setStyleSheet("position: relative;\n"
"width: 800px;\n"
"height: 800px;\n"
"\n"
"background: #444444;\n"
"box-sizing: border-box;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #EBBA0F;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, -1, -1, 100)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineGo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineGo.setMaximumSize(QtCore.QSize(404, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineGo.setFont(font)
        self.lineGo.setStyleSheet("border: 1px solid #EBBA0F;\n"
"box-sizing: border-box;\n"
"border-radius: 20px;\n"
"font-size: 20px;\n"
"color: #ebba0f;")
        self.lineGo.setObjectName("lineGo")
        self.horizontalLayout.addWidget(self.lineGo)
        self.ButtonGo = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonGo.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonGo.setFont(font)
        self.ButtonGo.setStyleSheet("background: #EBBA0F;\n"
"border-radius: 15px;\n"
"color: #444444;")
        self.ButtonGo.setObjectName("ButtonGo")
        self.horizontalLayout.addWidget(self.ButtonGo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineLogin.setMaximumSize(QtCore.QSize(404, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineLogin.setFont(font)
        self.lineLogin.setStyleSheet("border: 1px solid #EBBA0F;\n"
"box-sizing: border-box;\n"
"border-radius: 20px;\n"
"font-size: 20px;\n"
"color:#ebba0f;")
        self.lineLogin.setPlaceholderText("")
        self.lineLogin.setObjectName("lineLogin")
        self.horizontalLayout_2.addWidget(self.lineLogin)
        self.ButtonCopy_login = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonCopy_login.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonCopy_login.setFont(font)
        self.ButtonCopy_login.setStyleSheet("background: #EBBA0F;\n"
"border-radius: 15px;\n"
"color: #444444;")
        self.ButtonCopy_login.setObjectName("ButtonCopy_login")
        self.horizontalLayout_2.addWidget(self.ButtonCopy_login)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineDomain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDomain.setMaximumSize(QtCore.QSize(404, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineDomain.setFont(font)
        self.lineDomain.setStyleSheet("border: 1px solid #EBBA0F;\n"
"box-sizing: border-box;\n"
"border-radius: 20px;\n"
"font-size: 20px;\n"
"color:#ebba0f;")
        self.lineDomain.setPlaceholderText("")
        self.lineDomain.setObjectName("lineDomain")
        self.horizontalLayout_3.addWidget(self.lineDomain)
        self.ButtonCopy_domain = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonCopy_domain.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonCopy_domain.setFont(font)
        self.ButtonCopy_domain.setStyleSheet("background: #EBBA0F;\n"
"border-radius: 15px;\n"
"color: #444444;")
        self.ButtonCopy_domain.setObjectName("ButtonCopy_domain")
        self.horizontalLayout_3.addWidget(self.ButtonCopy_domain)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "E-mail Breaker"))
        self.lineGo.setPlaceholderText(_translate("MainWindow", "Paste e-mail"))
        self.ButtonGo.setText(_translate("MainWindow", "Go"))
        self.ButtonCopy_login.setText(_translate("MainWindow", "Copy"))
        self.ButtonCopy_domain.setText(_translate("MainWindow", "Copy"))
